name: Keep Render Alive
on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch: # 加上这行，就能在页面上手动触发了
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping my blog
        run: curl -s https://my-halo-blog.onrender.com > /dev/null 2>&1
